version: "3.4"
services:
  consul-server-1:
    container_name: consul-server-1
    build:
      context: consul-server
    ports:
      - "8500:8500"
      - "8600:8600/udp"
  backend-service:
    container_name: backend-service
    build:
      context: backend-service
    environment:
      CONSUL_SERVER_HOST: consul-server-1
  frontend-service:
    container_name: frontend-service
    build:
      context: frontend-service
    ports:
      - "8080:80"
    environment:
      CONSUL_SERVER_HOST: consul-server-1
